// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'App-logo-spin': string;
  'dragDropInlineEdit': string;
}
const cssExports: CssExports;
export default cssExports;
